### ISSUE TITLE
.NET Standard would allow the package to be consumed by more folks

### ISSUE THREAD

**Issue by gjmoyer** [drwatson1/adfs-metadata#1]
Thank you for this great piece of code!  I was wondering if you would consider updating your NuGet pkg to  be compatible with .NET Standard and not just .NET Core.  I think all you need to do is update the project type, as all code is compatible.  Thank you!

**Comment by drwatson1** [comment]
It's a good point. I'll do it as soon as I will have time for this. This week, I think. 
Of course, you can create a PR for that, so I will create and publish pkg soon.

Thank you for your suggestion!

**Comment by drwatson1** [comment]
[Done](https://github.com/drwatson1/adfs-metadata/releases/tag/v1.1.2)
Check this out and let me know does it work for you.

**Comment by gjmoyer** [comment]
That is super!  Thank you so much for doing this so quickly.
